### ISSUE TITLE
Windows file path problem in watch

### ISSUE THREAD

**Issue by dtomaszewski** [justinsisley/mjml-utils#2]
Hello,

There is problem with mju --watch  on windows machne. It is caused by different path separators than on Linux machines. Problem is in watcher/index.js

this is ugly solution how to solve the problem on windows : 

`function onChange(filePath, outputDir) {
  build(filePath.replace(/\\/g,"/"), outputDir);
}`

**Comment by justinsisley** [comment]
Merged PR!

**Comment by dtomaszewski** [comment]
Hi, this issue is different than this in PR ;)

**Comment by dtomaszewski** [comment]
Thanks ! Cheers!

**Comment by dtomaszewski** [comment]
Could You also release it on npm ?

**Comment by justinsisley** [comment]
Released 0.3.1 on NPM with this fix. Good luck!
