### ISSUE TITLE
Feature Request: Filetype recognition and/or ignore path

### ISSUE THREAD

**Issue by MissFerrety** [justinsisley/mjml-utils#7]
Most of the hiccups I had when I first started using `mjml-utils` had to do with the fact that it kept throwing an error on what I finally determined was my Assets folder. It was looking for typical MJML markup in every single file, not just my base `.mjml` files. I believe it also tries to apply such rules to folders, because even moving all assets outside of the build folder with the exception of an include (still `.mjml`) still threw the error because it was in its own folder.

It would be great to not be trying to look for markup in non-related files/folders, and also would be nice to recognize partials (includes) as such, since according to MJML documentation, they do not require full markup.

Another solution would be to be able to include an option for ignore path(s) added to the `--build` and `--watch` commands to set in your `package.json` so it just skips those files/folders entirely.

**Comment by justinsisley** [comment]
It sounds like this could be broken down into a couple of issues. I'll outline them below. Please let me know if it's in line with your thinking, then I'll work to get them resolved.

1. The watcher watches for changes in all files (within the input directory) when it should only watch `*.mjml` files
2. This library needs to support the `<mj-include />` component and properly resolve its `path` attribute, regardless of the task that is being run

**Comment by MissFerrety** [comment]
Sounds about right. To clarify, the current use case is having an assets
folder inside the watched folder, currently throwing errors about the lack
of proper mjml scripting. And as a corollary, any partials inside such
folders, though they be of `.mjml` filetype, also should not throw an error
for lacking top-level tags.

Now how about some real pain-in-the-butt suggestions? Not sure if it's
inside your scope or realm of willingness, but the following would make
this a truly powerful and unique tool.

A simple duplicate command for assets would further streamline the build
process. If that were included, I'd propose optional settings specifying a
dupe folder (for assets like images) and a partials folder in the package
run scripts (since partials need only be rendered, not living in the
completed folder). You could also just require a standard naming convention
like "assets" and "includes".

I'm currently only just getting started with mjml, so I have a master raw
folder with everything at that root level. I can imagine, though, that not
much further down the line, I'd want to split everything further into
related folders and not want to constantly change my build/watch scripts,
in which case it would be necessary for the build command to dig down into
those folders. In this case, if the duplicate/partials features were
implemented, you'd need to either go the standard naming route or note that
their personal settings must remain constant across projects.

**Comment by justinsisley** [comment]
I apologize for the long delay in responding here. I've been preoccupied with a couple of products that I'm building.

v2.2.0 should have solved points 1 and 2 in my previous comment, therefore I'm going to close this issue.

So you know, I've separated my templates in a similar fashion to your suggestion in your last comment. My "core" email templates are in an "email" directory in my projects, and partial templates are kept in a "partials" sub-directory. Using the `<mj-include>` directive, this makes my email templates really easy to organize and maintain.

Thanks for the suggestions!
